/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package so.seta.fca.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import so.seta.fca.util.LoggerNew;
import so.seta.fca.entity.Result;
import so.seta.fca.util.Exports;
/**
 *
 * @author Roberto Federico
 */
public class ExportFrame extends javax.swing.JFrame {
    public static final ResourceBundle conf = ResourceBundle.getBundle("conf.conf");   
    public static final String PATH = conf.getString("path.log");
    public static LoggerNew LOGGER = new LoggerNew("FCA_TRACK",PATH);
    private static final long serialVersionUID = 1L;
    String periodo1;
    String periodo2;
    List<String[]> rsLavorazioni = new ArrayList();
    int counter;
    /**
     * Creates new form ExportFrame
     * @param frame
     */
    public ExportFrame(MainFrame frame) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        dataA = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        dataDa = new javax.swing.JFormattedTextField();
        Cerca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        risultato = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Export = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Data da:");

        dataA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat(""))));
        dataA.setInputVerifier(new InputVerifier() {
            public boolean verify(JComponent input) {
                if (!(input instanceof JFormattedTextField))
                return true; // give up focus
                return ((JFormattedTextField) input).isEditValid();
            }
        });
        dataA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Data a:");

        dataDa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        dataDa.setInputVerifier(new InputVerifier() {
            public boolean verify(JComponent input) {
                if (!(input instanceof JFormattedTextField))
                return true; // give up focus
                return ((JFormattedTextField) input).isEditValid();
            }
        });
        dataDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDaActionPerformed(evt);
            }
        });

        Cerca.setText("Cerca");
        Cerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CercaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Esportazione Lavorazioni");

        risultato.setColumns(20);
        risultato.setRows(5);
        jScrollPane1.setViewportView(risultato);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Risultato:");

        Export.setText("Export");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataDa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(Export)
                                    .addComponent(Cerca)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cerca))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(Export))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(dataDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAActionPerformed

    private void dataDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDaActionPerformed

    private void CercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CercaActionPerformed
        // TODO add your handling code here:
        periodo1 = dataDa.getText();
        periodo2 = dataA.getText();
        rsLavorazioni = Exports.Excel_ExportLavorazioni(periodo1, periodo2);
        if (!rsLavorazioni.isEmpty()) {
            risultato.setText("Records Export Lavorazioni: " + rsLavorazioni.size());
        }
        
    }//GEN-LAST:event_CercaActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
        // TODO add your handling code here:
        Result ret = Exports.Excel_ExportLavorazioni(periodo1, periodo2, rsLavorazioni);
        if (ret.getEsito()) {
            risultato.append("\n ");
            risultato.append(ret.getMessaggio());                 
        }
    }//GEN-LAST:event_ExportActionPerformed

//    public void TestFunction() throws FileNotFoundException, IOException {
//         SXSSFWorkbook wb = new SXSSFWorkbook(100); // keep 100 rows in memory, exceeding rows will be flushed to disk
//        Sheet sh = wb.createSheet();
//        for(int rownum = 0; rownum < 10000; rownum++){
//            Row row = sh.createRow(rownum);
//            for(int cellnum = 0; cellnum < 10; cellnum++){
//                Cell cell = row.createCell(cellnum);
//                String address = new CellReference(cell).formatAsString();
//                cell.setCellValue(address);
//            }
//        }
        // Rows with rownum < 900 are flushed and not accessible
//        for(int rownum = 0; rownum < 900; rownum++){
//          Assert.assertNull(sh.getRow(rownum));
//        }
//        // ther last 100 rows are still in memory
//        for(int rownum = 900; rownum < 1000; rownum++){
//            Assert.assertNotNull(sh.getRow(rownum));
//        }
//        FileOutputStream out = new FileOutputStream("/temp/sxssf.xlsx");
//        wb.write(out);
//        out.close();
//        // dispose of temporary files backing this workbook on disk
//        wb.dispose();
//    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerca;
    private javax.swing.JButton Export;
    private javax.swing.JFormattedTextField dataA;
    private javax.swing.JFormattedTextField dataDa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea risultato;
    // End of variables declaration//GEN-END:variables
}
