/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package so.seta.fca.gui;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import so.seta.fca.entity.Result;
import so.seta.fca.util.ExcelImport;
import so.seta.fca.util.LoggerNew;
import static so.seta.fca.util.Utility.estraiEccezione;

/**
 *
 * @author Roberto Federico
 */
public class ImportFrame extends javax.swing.JFrame {
    public static final ResourceBundle conf = ResourceBundle.getBundle("conf.conf");   
    public static final String PATH = conf.getString("path.log");
    public static LoggerNew LOGGER = new LoggerNew("FCA_TRACK",PATH);
    private Cursor waitCursor = new Cursor(Cursor.WAIT_CURSOR);
    private Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
    private boolean waitCursorIsShowing;
    private String defaultButtonText = "Show Wait Cursor";
 
    // a default constructor
//    filechooser()
//    {
//    } 
    /**
     * Creates new form ImportFrame
     * @param frame
     */
    public ImportFrame(MainFrame frame) {
     
         
        initComponents();
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel *.xlsx", "xlsx");
        jFileChooser1.addChoosableFileFilter(filter);
                     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEsito = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jFileChooser1.setFileFilter(null);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Caricamento File");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Ricerca File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaEsito.setColumns(20);
        jTextAreaEsito.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEsito);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(248, 248, 248)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        if (waitCursorIsShowing)
//    {
//      // set the cursor back to the default
//      waitCursorIsShowing = false;
//      jButton2.setText(defaultButtonText);
//      this.setCursor(defaultCursor);
//    }
//    else
//    {
//      // change the cursor to the wait cursor
//      waitCursorIsShowing = true;
//      jButton2.setText("Back to Default Cursor");
//      this.setCursor(waitCursor);
//    }
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                 File file = jFileChooser1.getSelectedFile();
                 ExcelImport.ReadFromExcel(file.getAbsolutePath());
                 this.setCursor(waitCursor);
                 Result rit = ExcelImport.NewReadFromExcel(file.getAbsolutePath());
                 
                 if (rit.getEsito()) {
                    jTextAreaEsito.setText(rit.getMessaggio());
                 }
                 else {
                  jTextAreaEsito.setText("Prima Nessuna pratica caricata"); 
                 }
                 this.setCursor(defaultCursor);
                }
            catch (IOException ex) {
                LOGGER.log.severe(estraiEccezione(ex));
            }
            finally {
                 
//                this.setCursor(Cursor.DEFAULT_CURSOR);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
//    private void run(MainFrame frame) {
//          final JDialog loading = new JDialog(frame);
//            JPanel p1 = new JPanel(new BorderLayout());
//            p1.add(new JLabel("Please wait..."), BorderLayout.CENTER);
//            loading.setUndecorated(true);
//            loading.getContentPane().add(p1);
//            loading.pack();
//            loading.setLocationRelativeTo(frame);
//            loading.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
//            loading.setModal(true);
//
//            SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
//                @Override
//                protected String doInBackground() throws InterruptedException 
//                    /** Execute some operation */   
//                }
//                @Override
//                protected void done() {
//                    loading.dispose();
//                }
//            };
//            worker.execute(); //here the process thread initiates
//            loading.setVisible(true);
//
//try {
//    worker.get(); //here the parent thread waits for completion
//} catch (Exception e1) {
//    e1.printStackTrace();
//}
//    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ImportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ImportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ImportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ImportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ImportFrame(this).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextAreaEsito;
    // End of variables declaration//GEN-END:variables
}
