/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package so.seta.fca.gui;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Color;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import so.seta.fca.db.DB_FCA;
import so.seta.fca.entity.Lavorazione;
import so.seta.fca.entity.Pratica;
import so.seta.fca.entity.Utente;
/**
 *
 * @author Roberto Federico
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
private DB_FCA db = null;
private Utente usr = new Utente(); 

private Color circleColor = Color.GREEN; // Default color
private Pratica pratica = new Pratica();
private List<Lavorazione> lsLav;
String num_pra = "";
String id_pratica = "";
  public String user = "";
    /**
     * Creates new form MainFrame
     * @param user
     * @param conn
     */
    public MainFrame(String user, Connection conn) {
        this.lsLav = new ArrayList<>();
        this.db = new DB_FCA(conn);
        initComponents();
//        this.setLocation((int) ((this.getGraphicsConfiguration().getBounds().getWidth() - this.getWidth()) / 2), (int) ((this.getGraphicsConfiguration().getBounds().getHeight() - this.getHeight()) / 2));
        this.usr = db.getUser(user);
        enabledComponents();  
        this.btnRun.setVisible(false);
    }
    
    private void disabledComponents() {
        this.codicePratica.setText("");
        this.notaSospensione.setText("");
        this.jLabelEsito.setText("");
        this.saveEsito.setEnabled(false);
        this.esito.clearSelection();
        this.jPanel2.setVisible(false);
     //   DefaultTableModel model = (DefaultTableModel) this.tabellaLavorazioni.getModel();
     //   model.setRowCount(0);
    }
    private void enabledComponents() {
          
    if (this.usr.getRuolo().equalsIgnoreCase("OP")){ 
        jMenuBar1.setVisible(false);                            
    }
   
    jPanel2.setVisible(false);
         
       
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esito = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g)
            {
                super.paintComponent(g); // Do the original draw
                g.setColor(circleColor);
                // Draw a filled circle at coordinates (x, y) with a specified diameter
                int diameter = 50;
                g.fillOval(10, 10, diameter, diameter);
            }
        };
        saveEsito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRun = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabellaLavorazioni = new javax.swing.JTable();
        jRBNonLavorabile = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notaSospensione = new javax.swing.JTextArea();
        jRBSospensione = new javax.swing.JRadioButton();
        jRBChiusura = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEsito = new javax.swing.JLabel();
        codicePratica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loadPratica = new javax.swing.JButton();
        searchPratica = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FCA Track");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("Logout");
        logout.setMaximumSize(new java.awt.Dimension(88, 21));
        logout.setMinimumSize(new java.awt.Dimension(88, 21));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        saveEsito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveEsito.setText("Salva esito");
        saveEsito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEsitoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data da:");

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tabella lavorazioni");

        tabellaLavorazioni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabellaLavorazioni);

        esito.add(jRBNonLavorabile);
        jRBNonLavorabile.setText("Non lavorabile");
        jRBNonLavorabile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNonLavorabileActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nota sospensione:");

        notaSospensione.setColumns(20);
        notaSospensione.setRows(5);
        jScrollPane2.setViewportView(notaSospensione);

        esito.add(jRBSospensione);
        jRBSospensione.setText("Sospensione");

        esito.add(jRBChiusura);
        jRBChiusura.setText("Chiusura");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Azioni:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBNonLavorabile)
                            .addComponent(jRBChiusura)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRBSospensione)))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(458, 458, 458)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saveEsito)
                                    .addComponent(btnRun))))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 99, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBChiusura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBSospensione, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBNonLavorabile)))
                        .addGap(36, 36, 36)
                        .addComponent(saveEsito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRun))))
        );

        jLabelEsito.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelEsito.setForeground(new java.awt.Color(255, 102, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("N° pratica");

        loadPratica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loadPratica.setText("Carica pratica");
        loadPratica.setIconTextGap(2);
        loadPratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPraticaActionPerformed(evt);
            }
        });

        searchPratica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchPratica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchPratica.setText("Ricerca Pratica");
        searchPratica.setIconTextGap(1);
        searchPratica.setMaximumSize(new java.awt.Dimension(104, 21));
        searchPratica.setMinimumSize(new java.awt.Dimension(104, 21));
        searchPratica.setPreferredSize(new java.awt.Dimension(104, 21));
        searchPratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPraticaActionPerformed(evt);
            }
        });

        jMenu2.setText("Azioni");

        jMenuItem1.setText("Importa pratiche");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Esporta pratiche");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Sblocca Pratiche");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(codicePratica, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(loadPratica)
                        .addGap(44, 44, 44)
                        .addComponent(searchPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(586, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEsito, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(864, 864, 864))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPratica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codicePratica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loadPratica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEsito, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadPraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPraticaActionPerformed
        // TODO add your handling code here:
        loadPratica();
    }//GEN-LAST:event_loadPraticaActionPerformed
    private Color getColor(String stato) {
        switch (stato) {
            case "CH" :
            case "NL" :
                return Color.RED;                
            case "SO" :
                return Color.ORANGE;
            default:
             return Color.GREEN;
        }
    };
    
    private void loadPratica() {
        this.pratica = this.db.getPraticaDaLavorare();
        num_pra = this.pratica.getNum_pra();
        if (null == num_pra) {
            String msg = "Nessuna pratica da lavorare";
            this.jLabelEsito.setText(msg);
            return;
        }
        id_pratica = this.pratica.getIdPratica().toString();
        codicePratica.setText(num_pra);
        ElaboraPratica(num_pra);
    }
     private void ElaboraPratica(String numPratica) {
        this.lsLav = this.db.VerificaPratica(numPratica);
        String Esito = "";
        if (!this.lsLav.isEmpty()) {             
            Lavorazione pl = this.lsLav.get(0);
            Esito = pl.getEsito();
            this.tabellaLavorazioni.setModel(getParModelU1());
        } else {
            DefaultTableModel model = (DefaultTableModel) this.tabellaLavorazioni.getModel();
            model.setRowCount(0);
        }           
        circleColor = getColor(Esito);
        this.jPanel2.setVisible(true);
        this.saveEsito.setEnabled(true);
     }
     public DefaultTableModel getParModelU1() {
        try {
             DefaultTableModel defaultTableModel = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                    return false;
                }
            };
            defaultTableModel.addColumn("ESITO");
            defaultTableModel.addColumn("DATALAV");
            defaultTableModel.addColumn("OPERATORE");
            defaultTableModel.addColumn("NOTA");
            
           
            int i = 0;
            this.lsLav.forEach(lav ->{
                defaultTableModel.insertRow(i, new Object[]{lav.getEsito(),lav.getDataLavorazione(),lav.getUtente(),lav.getNota()});
            });
            return defaultTableModel;
        } catch (Exception ex) {
            Logger.getLogger(ex.getMessage());
        }
        return null;
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, "Importa pratiche da lavorare.",
//                    "Messaggio di conferma", JOptionPane.INFORMATION_MESSAGE);
         new ImportFrame(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//           JOptionPane.showMessageDialog(null, "Espoprta pratiche lavorate.",
//                    "Messaggio di conferma", JOptionPane.INFORMATION_MESSAGE);
        new ExportFrame(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
        this.db.sbloccaPratiche();
    }//GEN-LAST:event_btnRunActionPerformed

    private void saveEsitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEsitoActionPerformed
    if (jRBChiusura.isSelected() == false && jRBSospensione.isSelected() == false && jRBNonLavorabile.isSelected() == false) {
        JOptionPane.showMessageDialog(null, "Attenzione Selezionare un'azione !!!", "Warning", JOptionPane.WARNING_MESSAGE);
    }
        else {
        InserisciLavorazione();
        AggiornaStatoLavorazione();
        this.loadPratica.setText("Carica nuova pratica");
        this.disabledComponents();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveEsitoActionPerformed

     private void _logout() {
        this.dispose();
        this.db.closeDB();
        System.exit(0);
    }
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO  if (this.logout.isEnabled()) {
        int response = JOptionPane.showConfirmDialog(null, "Sicuro di volersi disconnettere dall'applicazione?", "Avviso",
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (response == 0) {
            this._logout();
        }        
    }//GEN-LAST:event_logoutActionPerformed

    private void jRBNonLavorabileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNonLavorabileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBNonLavorabileActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            int ret = db.sbloccaPratiche();        // TODO add your handling code here:
            System.out.println(ret);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void searchPraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPraticaActionPerformed
           // TODO add your handling code here:
           if (!"".equals(codicePratica.getText())) {
               ElaboraPratica(codicePratica.getText().trim());
           }
    }//GEN-LAST:event_searchPraticaActionPerformed

    public void InserisciLavorazione() {
        Lavorazione lav = new Lavorazione();
        lav.setNum_pra(codicePratica.getText());
        lav.setEsito(jRBSospensione.isSelected() ? "SO" :  jRBChiusura.isSelected() ? "CH" : "NL");
        lav.setUtente(this.usr.getUser());
        lav.setNota(notaSospensione.getText());
        boolean ret = db.insLavorazione(lav);
        
        if (ret) {
            String testo = "Lavorazione inserita correttamente";
            JOptionPane.showMessageDialog(null, testo, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
            
                
    }
    public void AggiornaStatoLavorazione() {
        db.setStatoPratica(id_pratica, "E");
    }
   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JTextField codicePratica;
    private javax.swing.ButtonGroup esito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEsito;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBChiusura;
    private javax.swing.JRadioButton jRBNonLavorabile;
    private javax.swing.JRadioButton jRBSospensione;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton loadPratica;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea notaSospensione;
    private javax.swing.JButton saveEsito;
    private javax.swing.JButton searchPratica;
    public javax.swing.JTable tabellaLavorazioni;
    // End of variables declaration//GEN-END:variables
}
